#!/bin/bash

# controller のあるディレクトリへ
cd /Users/sky-legacy/devWorks/others/sashimihossu/fridge_draft/app/controllers

# このスクリプトが実行される際に標準入力として流れてきたメールをtxtに保存し、
# これを読むcontrollerのメソッドを叩く
if [ -p /dev/stdin ] ; then
    nowtime=`date "+%Y%m%d%H%M%S"`
    cat - > tmp/${nowtime}_mail.txt
    rails runner -e development ItemsController.recvmail("$nowtime")
fi
